name: build_and_push

on:
    release:
        types:
            - published

jobs:
    build_and_push:
        strategy:
          matrix:
            platform: [amd64, arm64]
            include:
              - platform: amd64
                runner: blacksmith-4vcpu-ubuntu-2204
                docker_platform: linux/amd64
              - platform: arm64
                runner: blacksmith-4vcpu-ubuntu-2204-arm
                docker_platform: linux/arm64

        runs-on: ${{ matrix.runner }}

        environment:
          name: Production
          url: 'https://iconify.tools.logitud.cloud'

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install

            - name: Prepare icons
              run: npm run importer

            - name: Validate src and icons directories
              run: |
                echo "🔍 Vérification pré-build…"
                for d in src icons; do
                  if [ ! -d "$d" ]; then
                    echo "❌ Directory '$d' not found in repo."
                    exit 1
                  fi
                  if [ -z "$(ls -A "$d")" ]; then
                    echo "❌ Directory '$d' is empty."
                    exit 1
                  fi
                done
                echo "✅ src and icons directories are present and non-empty."

            - name: Login to registry
              uses: docker/login-action@v3
              with:
                username: 'nologin'
                password: '${{ secrets.REGISTRY_PASS }}'
                registry: '${{ secrets.REGISTRY_URL }}'

            - name: Build and push Image
              uses: useblacksmith/build-push-action@v1
              with:
                push: true
                tags: |
                  ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPO }}/${{ github.repository }}:${{ matrix.platform }}-${{ github.ref_name }}
                  ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPO }}/${{ github.repository }}:${{ matrix.platform }}-latest
                platforms: ${{ matrix.docker_platform }}
                build-args: |
                  ARCH=${{ matrix.platform }}
                  ICONIFY_API_VERSION=${{ github.ref_name }}
                  TAG_SUFFIX=default
                  BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")"
